let productos = []; let carrito = []; let productoSeleccionado = null; const numeroEmpresa = 9231389333;
fetch('productos.json').then(r=>r.json()).then(data=>{productos=data;renderCatalogo();});
function renderCatalogo(){const c=document.getElementById('catalogo');c.innerHTML='';productos.forEach(p=>{const card=document.createElement('div');card.className='card';const carousel=document.createElement('div');carousel.className='carousel';p.imagen.forEach((src,i)=>{const img=document.createElement('img');img.src=src;img.alt=p.nombre;if(i===0)img.classList.add('active');carousel.appendChild(img);});const prev=document.createElement('button');prev.textContent='<';prev.className='prev';const next=document.createElement('button');next.textContent='>';next.className='next';carousel.appendChild(prev);carousel.appendChild(next);prev.addEventListener('click',()=>cambiarImagen(carousel,-1));next.addEventListener('click',()=>cambiarImagen(carousel,1));const content=document.createElement('div');content.className='card-content';const nombre=document.createElement('h2');nombre.textContent=p.nombre;const precio=document.createElement('p');precio.textContent=`Precio: $${p.precio}`;const tallas=document.createElement('p');tallas.textContent=`Tallas: ${p.tallas.join(', ')}`;content.appendChild(nombre);content.appendChild(precio);content.appendChild(tallas);const btn=document.createElement('button');btn.className='agregar-btn';btn.textContent='Agregar al carrito';btn.addEventListener('click',()=>mostrarPopupAgregar(p));content.appendChild(btn);if(p.soldOut){const sold=document.createElement('div');sold.className='soldout-text';sold.textContent='SOLD OUT';card.appendChild(sold);btn.disabled=true;}card.appendChild(carousel);card.appendChild(content);c.appendChild(card);});}
function cambiarImagen(carousel,d){const imgs=carousel.querySelectorAll('img');let i=[...imgs].findIndex(img=>img.classList.contains('active'));imgs[i].classList.remove('active');i=(i+d+imgs.length)%imgs.length;imgs[i].classList.add('active');}
function mostrarPopupAgregar(p){productoSeleccionado=p;document.getElementById('popup-agregar').classList.remove('oculto');const colorSel=document.getElementById('color-select');const tallaSel=document.getElementById('talla-select');colorSel.innerHTML='';tallaSel.innerHTML='';p.colores.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;colorSel.appendChild(o);});p.tallas.forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t;tallaSel.appendChild(o);});}
document.getElementById('cancelar-agregar').onclick=()=>document.getElementById('popup-agregar').classList.add('oculto');
document.getElementById('confirmar-agregar').onclick=()=>{const color=document.getElementById('color-select').value;const talla=document.getElementById('talla-select').value;const cantidad=parseInt(document.getElementById('cantidad-input').value);agregarAlCarrito(productoSeleccionado,color,talla,cantidad);document.getElementById('popup-agregar').classList.add('oculto');};
function agregarAlCarrito(p,color,talla,cantidad){const e=carrito.find(i=>i.id===p.id&&i.color===color&&i.talla===talla);if(e){e.cantidad+=cantidad;}else{carrito.push({id:p.id,nombre:p.nombre,color,talla,cantidad});}renderCarrito();}
function renderCarrito(){const cont=document.getElementById('carrito-items');cont.innerHTML='';carrito.forEach((i,index)=>{const div=document.createElement('div');div.className='carrito-item';div.textContent=`${i.nombre} | ${i.cantidad} pz | Color: ${i.color}`;div.style.backgroundColor=index%2===0?'#f9f9f9':'#eaeaea';cont.appendChild(div);});}
document.getElementById('abrir-carrito').onclick=()=>document.getElementById('carrito-slider').classList.add('abierto');
document.getElementById('cerrar-carrito').onclick=()=>document.getElementById('carrito-slider').classList.remove('abierto');
document.getElementById('hacer-pedido').onclick=()=>document.getElementById('popup-pedido').classList.remove('oculto');
document.getElementById('cancelar-pedido').onclick=()=>document.getElementById('popup-pedido').classList.add('oculto');
document.getElementById('enviar-pedido').onclick=()=>{const nombre=document.getElementById('nombre').value;const direccion=document.getElementById('direccion').value;const numeroContacto=document.getElementById('numero').value;const cp=document.getElementById('cp').value;const municipio=document.getElementById('municipio').value;const estado=document.getElementById('estado').value;const recoger=document.getElementById('recoger').checked?'Recoger en tienda':'Entrega a domicilio';let mensaje=`Pedido de ${nombre}%0AContacto: ${numeroContacto}%0A${recoger}%0A${direccion}, CP: ${cp}, ${municipio}, ${estado}%0A`;carrito.forEach(i=>{mensaje+=`ID: ${i.id} | ${i.nombre} | Color: ${i.color} | Talla: ${i.talla} | Cantidad: ${i.cantidad}%0A`;});const url=`https://wa.me/${numeroEmpresa}?text=${mensaje}`;window.open(url,'_blank');};